---
version: v1alpha1
machine:
  features:
    kubePrism:
      enabled: true
      port: 7445
    kubernetesTalosAPIAccess:
      enabled: true
      allowedKubernetesNamespaces:
        - system-upgrade
      allowedRoles:
        - os:admin
  files:
    - op: overwrite
      path: /etc/nfsmount.conf
      permissions: 0o644
      content: |
        [ NFSMount_Global_Options ]
        nfsvers=3
        hard=True
        nconnect=8
        noatime=True
        nolock=True
        rsize=1048576
        wsize=1048576
    - path: /etc/cri/conf.d/20-customization.part
      op: create
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
  install:
    image: factory.talos.dev/metal-installer/81ffc23ba1f0113dcf159f5b4d82c41a3058818a0cdc70450adb387617bd9712:v1.13.5
    wipe: true
cluster:
  controlPlane:
    endpoint: https://k8s.home:6443
  apiServer:
    certSANs:
      - k8s.home
      - 10.0.20.11
      - 10.0.20.12
      - 10.0.20.13
  network:
    cni:
      name: none
  proxy:
    disabled: true
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp0s31f6
up: true
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp0s31f6
---
apiVersion: v1alpha1
kind: VLANConfig
name: enp0s31f6.40
parent: enp0s31f6
vlanID: 40
up: true